apiVersion: apps/v1
kind: Deployment
metadata:
  name: tarif-deployment
  labels:
    app: tarif
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tarif
  template:
    metadata:
      labels:
        app: tarif
    spec:
      containers:
      - name: tarif
        image: coconut33/tarif:latest
        ports:
        - containerPort: 8085
        env:
        - name: SERVER_PORT 
          value: "8085"
